# Generated by Django 5.1.7 on 2025-04-29 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_watch_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('short_content', models.TextField(verbose_name='Краткое содержание')),
                ('full_content', models.TextField(verbose_name='Полное содержание')),
                ('published', models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата публикации')),
            ],
        ),
    ]
