# Generated by Django 5.1.7 on 2025-05-06 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='watch',
            name='published',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, verbose_name='Дата публикации'),
        ),
    ]
